name: Scheduled Update Holidays

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  updateHolidays:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Library Install
        run: sudo apt-get install nkf

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Update Holiday
        run: make updateHolidays

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: update holidays
          title: Update Holiday
          base: updated_holiday